AWSTemplateFormatVersion: "2010-09-09"
Description: >
  "Template for ALB"

Parameters:
  MyVpcId:
    Description: "ID of Virtual Private Cloud (VPC)"
    Type: String
  PublicSubnets:
    Description: "List of Public Subnets"
    Type: String
  SGalb:
    Description: "Security Group for ALB"
    Type: String

Resources:
  MyTgALB:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: "instance"
      Name: "MY-TGALB"
      Protocol: "HTTP"
      Port: 80
      VpcId: !Ref MyVpcId
      HealthCheckPath: "HTTP1"
      HealthCheckProtocol: "HTTP"
      HealthCheckPath: "/"
      Tags:
        - Key: "Name"
          Value: !Sub "MyTgALB-${AWS::StackName}"

  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      Name: "MyALB"
      Scheme: "internet-facing"
      IpAddressType: "ipv4"
      Subnets: !Split [",",!Ref PublicSubnets]
      SecurityGroups:
        - !Ref SGalb
      Tags:
        - Key: "Name"
          Value: !Sub "MyALB-${AWS::StackName}"
  
  MyALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 80
      Protocol: "HTTP"
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref MyTgALB
      LoadBalancerArn: !Ref MyALB

Outputs:
  ALBDns:
    Description: "URL to ALB"
    Value: !Sub "http://${MyALB.DNSName}"
  ALBtg:
    Description: "Reference Target group of ALB"
    Value: !Ref MyTgALB