AWSTemplateFormatVersion: "2010-09-09"
Description: >
  "Template for ALB autoscaling"

Parameters:
  ImageId:
    Description: "AMI ID"
    Type: String
  KeyName:
    Description: "Assorted Key pair name"
    Type: String
  SGwebserver:
    Description: "Security Group of Mysql server"
    Type: List<String>
  ASGMax:
    Description:  "Max Autoscaling instances"
    Type: String
  ASGMin:
    Description:  "Min Autoscaling instances"
    Type: String
  ASGDesired:
    Description:  "Desired Autoscaling instances"
    Type: String
  MyTgALB:  
    Description:  "NLB Target group"
    Type: String
  PrivateSubnets: 
    Description:  "List Private subnets"
    Type: String
  MyNLBdns:
    Description: "NLB DNS String"
    Type: String
  EnvName:
    Description: "Environment tag"
    Type: String
Resources:
  MyLaunchconfigweb:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      LaunchConfigurationName: !Sub "MyLaunchConfigweb-${EnvName}"
      ImageId: !Ref ImageId
      InstanceType: "t2.micro"
      KeyName: !Ref KeyName
      SecurityGroups: !Ref SGwebserver
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt update && upgrade
            sudo apt install -y apache2
            sudo systemctl restart apache2
            sudo apt install -y php libapache2-mod-php php-mysql
            sudo apt install -y php-curl php-gd php-xml php-mbstring  php-xmlrpc php-zip php-soap php-intl
            sudo rm /var/www/html/index.html
            cd ~
            sudo curl -O https://wordpress.org/latest.tar.gz
            sudo tar xzvf latest.tar.gz
            sudo cp -R wordpress/* /var/www/html/
            sudo chmod -R 777 /var/www/html/
            sudo chown -R www-data:www-data /var/www/html/
            sudo systemctl restart apache2
            sudo cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
            sudo sed -i "s/database_name_here/WordPressDB/g" /var/www/html/wp-config.php
            sudo sed -i "s/username_here/WordPressUser/g" /var/www/html/wp-config.php
            sudo sed -i "s/password_here/welcome123/g" /var/www/html/wp-config.php
            sudo sed -i "s/localhost/${MyNLBdns}/g" /var/www/html/wp-config.php
            cd /
            echo "<html><head><title>Health Check</title></head><body><h1>Healthy</h1></body></html>" >> health.html
            sudo chmod +x health.html
            sudo systemctl restart apache2
    #DependsOn: MyNLB
  MyAutoscalingGroupweb:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub "AutoscaleGroupweb-${EnvName}"
      MaxSize: !Ref ASGMax
      MinSize: !Ref ASGMin
      DesiredCapacity: !Ref ASGDesired
      TargetGroupARNs:
        - !Ref MyTgALB
      LaunchConfigurationName: !Ref MyLaunchconfigweb
      VPCZoneIdentifier: !Split [",",!Ref PrivateSubnets]