AWSTemplateFormatVersion: "2010-09-09"
Description: >
  "Template for NLB"

Parameters:
  MyVpcId:
    Description: "ID of Virtual Private Cloud (VPC)"
    Type: String
  PrivateSubnets:
    Description: "Private Subnet List"
    Type: String
  EnvName:
    Description: "Environment tag"
    Type: String
Resources:
  MyTgNLB:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: "instance"
      Name: !Sub "MyTgNLB-${EnvName}"
      Protocol: "TCP"
      Port: 3306
      VpcId: !Ref MyVpcId
      HealthCheckProtocol: "TCP"
      Tags:
        - Key: "Name"
          Value: !Sub "MyTgNLB-${AWS::StackName}"

  MyNLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: "application"
      Name: !Sub "MyNLB-${EnvName}"
      Scheme: "internal"
      IpAddressType: "ipv4"
      Subnets: !Split [",",!Ref PrivateSubnets]
      Tags:
        - Key: "Name"
          Value: !Sub "MyNLB-${AWS::StackName}"
  
  MyNLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Port: 3306
      Protocol: "TCP"
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref  MyTgNLB
      LoadBalancerArn: !Ref MyNLB

Outputs:
  NLBDns:
    Description: "URL to NLB"
    Value: !Sub "${MyNLB.DNSName}"
  NLBtg:
    Description: "Reference Target group of NLB"
    Value: !Ref MyTgNLB